### ISSUE TITLE
Deploy GitHub Pages

### ISSUE THREAD

**Issue by an-jorge** [Cristiano-Master/Curriculum-ReactJS-#1]
​Tentei rodar offline e não funcionou senti a falta de um README. 😓
Um ponto muito importante é poder fazer o deploy do seu site estático​ no GitHub pages ou em outras soluções.

![316061112](https://user-images.githubusercontent.com/10496881/203340688-496fd559-b5b5-4716-88bb-fe30b675ed83.jpg)

**Comment by Cristiano-Master** [comment]
https://tchanopycv.netlify.app/
tente rodar agora.

**Comment by Cristiano-Master** [comment]
usando o link acima, fiz um Deploy com server externo.

**Comment by an-jorge** [comment]
O link externo funciona, o que aconteceu com a do GitHub ?

**Comment by Cristiano-Master** [comment]
GitHub - Cristiano-Master/Curriculum-ReactJS-: Este é um curriculum feito
em ReactJs, espero que gostes
<https://github.com/Cristiano-Master/Curriculum-ReactJS->

Tente agora nesse.

António Jorge ***@***.***> escreveu no dia quinta, 19/01/2023
à(s) 15:55:

**Comment by Cristiano-Master** [comment]
https://github.com/Cristiano-Master/Curriculum-ReactJS-.git

Crypto Capital Venture ***@***.***> escreveu no dia
sexta, 20/01/2023 à(s) 09:07:
